require("dz/[HYD]dz_Barrel_chicken_esp")
require("dz/[HYD]all_betterboxes")
require("dz/[HYD]dz_auto_respawn")
require("dz/[HYD]dz_crosshair_indicators")
require("dz/[HYD]dz_esp")
require("dz/[HYD]dz_highscores")
require("dz/[HYD]dz_plisthack")
require("dz/[HYD]dz_remove_grass")
---require("dz/[HYD]dz_shieldbot")
require("dz/[HYD]dz_speedHVH")
client.color_log(255, 0, 255, "DangerZone GODLIKE Dragon Public.lua loaded successfully.")
client.color_log(255, 0, 255, "Lua Version:V6.0[Release] Last Update Time:2025/1/19")
client.color_log(255, 0, 255, "GL&HF!")
client.color_log(255, 0, 255, "Author:HuYiDao. Owned by DangerZoneCoreTeam.")
client.color_log(255, 0, 255, "OurWebSite:https://www.dz8.co/")
